services:
  
  app:
    container_name: app
    image: aplus-dm-v2.2.1
    profiles: ["prod"]
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      CACHE_EXPIRATION_HOURS: ${CACHE_EXPIRATION_HOURS}
      REDIS_URL: ${REDIS_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      CERTAIN_API_BASE: ${CERTAIN_API_BASE}
      DEFAULT_ACCOUNT_CODE: ${DEFAULT_ACCOUNT_CODE}
      CERTAIN_API_USERNAME_ENCRYPTED: ${CERTAIN_API_USERNAME_ENCRYPTED}
      CERTAIN_API_PASSWORD_ENCRYPTED: ${CERTAIN_API_PASSWORD_ENCRYPTED}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8080:8080"
    restart: unless-stopped

  postgres:
    container_name: postgres
    profiles: ["dev"]
    image: postgres:latest
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
  nginx:
    container_name: nginx
    profiles: ["prod"]
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Contains cert.pem and key.pem
    ports:
      - "443:443"
    depends_on:
      - app

volumes:
  pg_data:
