version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Contains cert.pem and key.pem
    ports:
      - "443:443"
    depends_on:
      - app

volumes:
  pg_data:
